# HANDLING NUMERICAL DATA

**Overflow error**

Overflow happens when we try to push more items on a stack than it can hold

**Underflow**

Underflow happens when we try to pop an item from an empty stack

**Rescaling**
distrubtion of data should not change



**Types of SCALERS**

Standard Features: z=x-u/s
Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual features do not more or less look like standard normally distributed data

**MinMaxScaler**
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min

largest occurring data point corresponds to the maximum value (meaning the maximun value that occurs more type in the data will be the maximum value of the data example [100,99,98,99,99,99,99,95,23,45,67]then 99 will be the maximum value of the data )
same for min
if theres no negative value then minmaxscaler is used


**Outlier**
An outlier is an observation that lies an abnormal distance from other values in a random sample from a population (outliers are lying values)


**For DataSet i have used titanic dataset
and at places i have used pasanger id to calculate mean standard diveation you can use other data and various function accoding to your data**

#  Rescaling a feature

**MinMaxScaler**

In [ ]:
import numpy as np
from sklearn import preprocessing

feature =np.array([
    [-500.5],
    [-100.1],
    [0],
    [100.1],
    [900.9]
    ])
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scaler.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

**Using Dataset**

In [ ]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('/content/test (4).csv')
feature = df['Fare']

feature = feature.values.reshape(-1, 1)
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scaler.fit_transform(feature)
scaled_feature
# Slice the array to get the first 5 elements
sliced_array = scaled_feature[:5]
# Print the sliced array
print(sliced_array)




[[0.01528158]
 [0.01366309]
 [0.01890874]
 [0.01690807]
 [0.0239836 ]]


#  Standardizing a Feature
**[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler)**

In [ ]:
import numpy as np
from sklearn import preprocessing
scaler = preprocessing. StandardScaler()
standardized = scaler.fit_transform(feature)
feature=np.array([
    [-100.1],
    [-200.2],
    [500.5],
    [600.6],
    [900.9]])
print("Mean {}".format(round (standardized.mean())))
print("Standard deviation: {}".format(standardized.std()))

Mean 0
Standard deviation: 1.0


**using the RobustScaler method: **

In [ ]:
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(feature)


array([[-0.85714286],
       [-1.        ],
       [ 0.        ],
       [ 0.14285714],
       [ 0.57142857]])

**Using Dataset**

In [ ]:
import pandas as pd
from sklearn import preprocessing
scaler = preprocessing. StandardScaler()

df = pd.read_csv('/content/test (4).csv')
feature = df['PassengerId']
feature =np.array(feature).reshape(-1, 1)

standardized = scaler.fit_transform(feature)
print("Mean {}".format(round (standardized.mean())))
print("Standard deviation: {}".format(standardized.std()))

Mean 0
Standard deviation: 0.9999999999999999


In [ ]:
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(feature)
transformed_feature = robust_scaler.transform(feature)

# Slice the transformed data
sliced_array = transformed_feature[:5]

# Print the sliced array
print(sliced_array)

[[-1.        ]
 [-0.99520384]
 [-0.99040767]
 [-0.98561151]
 [-0.98081535]]


# Normalizing Observations

In [ ]:
import numpy as np
from sklearn.preprocessing import Normalizer
features = np.array([
    [0.5,0.5],
    [1.1,3.4],
    [1.5,20.2],
    [1.63,34.4],
    [10.9,3.3],
])
normalizerl1=Normalizer(norm="l1")
normalizerl2=Normalizer(norm="l2")
normalizerMax=Normalizer(norm="max")
print("l1 normalization\n",normalizerl1.transform(features))
print("\nl2 normalization\n",normalizerl2.transform(features))
print("\nmax normalization\n",normalizerMax.transform(features))



l1 normalization
 [[0.5        0.5       ]
 [0.24444444 0.75555556]
 [0.06912442 0.93087558]
 [0.04524008 0.95475992]
 [0.76760563 0.23239437]]

l2 normalization
 [[0.70710678 0.70710678]
 [0.30782029 0.95144452]
 [0.07405353 0.99725427]
 [0.04733062 0.99887928]
 [0.95709822 0.28976368]]

max normalization
 [[1.         1.        ]
 [0.32352941 1.        ]
 [0.07425743 1.        ]
 [0.04738372 1.        ]
 [1.         0.30275229]]


**Using Dataset**

In [ ]:
import pandas as pd
from sklearn.preprocessing import Normalizer

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/test (4).csv')

# Extract the 'PassengerId' column and reshape it for normalization
feature = df['PassengerId']
feature = np.array(feature).reshape(-1, 1)

# Initialize Normalizers
normalizer_l1 = Normalizer(norm="l1")
normalizer_l2 = Normalizer(norm="l2")
normalizer_max = Normalizer(norm="max")

# Perform normalization
normalized_l1 = normalizer_l1.transform(feature)
normalized_l2 = normalizer_l2.transform(feature)
normalized_max = normalizer_max.transform(feature)

# Print a portion of the transformed data
print("l1 normalization\n", normalized_l1[:5])  # Printing first 5 rows
print("\nl2 normalization\n", normalized_l2[:5])  # Printing first 5 rows
print("\nmax normalization\n", normalized_max[:5])  # Printing first 5 rows


l1 normalization
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

l2 normalization
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

max normalization
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


#  Grouping Observations Using Clustering

In [ ]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
features,_= make_blobs(n_samples = 50,
                     n_features=2,
                     centers=3,
                     random_state=1)
df=pd.DataFrame(features,columns=["feature_1","feature_2"])
clusterer=KMeans(3,random_state=0)
clusterer.fit(features)
df["group"]=clusterer.predict(features)
df.head()


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

**Using Dataset**

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/test (4).csv')

# Extract the 'PassengerId' column and reshape it for clustering
features = df['PassengerId']
features = np.array(features).reshape(-1, 1)

# Create a DataFrame with the features
df_features = pd.DataFrame(features, columns=["PassengerId"])

# Initialize and fit KMeans clustering
clusterer = KMeans(n_clusters=3, random_state=0)
clusterer.fit(features)

# Add cluster labels to the DataFrame
df_features["group"] = clusterer.labels_

# Display the DataFrame with cluster labels
print(df_features.head())


   PassengerId  group
0          892      0
1          893      0
2          894      0
3          895      0
4          896      0


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


# Deleteing Observations with Missing Values

In [ ]:
import numpy as np
features = np.array([
    [1.1,11.1],
    [2.2,22.2],
    [3.3,33.3],
    [np.nan,55]
])
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3]])

**Using Dataset**

In [ ]:
import pandas as pd


# Read the CSV file into a DataFrame
df = pd.read_csv('/content/test (4).csv')

# Extract the 'PassengerId' column
features = df['PassengerId']

# Reshape the feature for clustering
features = np.array(features).reshape(-1, 1)

# Remove rows with NaN values
features_cleaned = features[~np.isnan(features).any(axis=1)]

# Slice the cleaned features array to display a portion of it
portion_of_features = features_cleaned[:10]  # Displaying the first 10 rows

# Display the sliced portion of the cleaned features
print(portion_of_features)



[[892]
 [893]
 [894]
 [895]
 [896]
 [897]
 [898]
 [899]
 [900]
 [901]]


# Imputing Missing Value
[SimpleImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html)

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples=1000, n_features=2, random_state=1)

# standardize the features
scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

# replace the first feature's first value with a missing value
true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

# create imputer
mean_imputer = SimpleImputer(strategy="mean")
median_imputer = SimpleImputer(strategy="median")
mode_imputer = SimpleImputer(strategy="most_frequent")

# impute values
features_mean_imputed = mean_imputer.fit_transform(standardized_features)
features_median_imputed = median_imputer.fit_transform(standardized_features)
features_mode_imputed = mode_imputer.fit_transform(standardized_features)

# compare true and imputed values
print("True Value: {}".format(true_value))
print("Mean Imputed Value: {}".format(features_mean_imputed[0, 0]))
print("Median Imputed Value: {}".format(features_median_imputed[0, 0]))
print("Mode Imputed Value: {}".format(features_mode_imputed[0, 0]))

True Value: 0.8730186113995938
Mean Imputed Value: -0.000873892503901796
Median Imputed Value: -0.23980483042535553
Mode Imputed Value: -1.9059115647714258


**Using Dataset**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/test (4).csv')

# Extract the 'PassengerId' column
features = df['PassengerId']

# Reshape the feature for clustering
features = np.array(features).reshape(-1, 1)

# Apply imputation
# Create imputer
mean_imputer = SimpleImputer(strategy="mean")
median_imputer = SimpleImputer(strategy="median")
mode_imputer = SimpleImputer(strategy="most_frequent")

# Impute values
features_mean_imputed = mean_imputer.fit_transform(features)
features_median_imputed = median_imputer.fit_transform(features)
features_mode_imputed = mode_imputer.fit_transform(features)

# Compare true and imputed values for the first element
print("Mean Imputed Value: {}".format(features_mean_imputed[0, 0]))
print("Median Imputed Value: {}".format(features_median_imputed[0, 0]))
print("Mode Imputed Value: {}".format(features_mode_imputed[0, 0]))


Mean Imputed Value: 892.0
Median Imputed Value: 892.0
Mode Imputed Value: 892
